const dogs = [
    {
      name: "Rex",
      avatar: "images/dog-rex.jpg",
      age: 25,
      bio: "Art. Literature. Natural wine. Yoga.",
      hasBeenSwiped: false,
      hasBeenLiked: false,
    },
    {
      name: "Bella",
      avatar: "images/dog-bella.jpg",
      age: 43,
      bio: "Yup, that's my owner. U can meet him if you want",
      hasBeenSwiped: false,
      hasBeenLiked: false,
    },
    {
      name: "Teddy",
      avatar: "images/dog-teddy.jpg",
      age: 30,
      bio: "How you doin?",
      hasBeenSwiped: false,
      hasBeenLiked: false,
    },
    {
      name: "John",
      avatar: "images/one.jpg",
      age: 25,
      bio: "Art. Literature. Natural wine. Yoga.",
      hasBeenSwiped: false,
      hasBeenLiked: false,
    },
    {
      name: "Tiger",
      avatar: "images/two.jpg",
      age: 43,
      bio: "Yup, that's my owner. U can meet him if you want",
      hasBeenSwiped: false,
      hasBeenLiked: false,
    },
    {
      name: "Ale",
      avatar: "images/three.jpg",
      age: 43,
      bio: "Yup, that's my owner. U can meet him if you want",
      hasBeenSwiped: false,
      hasBeenLiked: false,
    },
    {
      name: "Bella",
      avatar: "images/four.jpg",
      age: 43,
      bio: "Yup, that's my owner. U can meet him if you want",
      hasBeenSwiped: false,
      hasBeenLiked: false,
    },
    {
      name: "Tom",
      avatar: "images/five.jpg",
      age: 43,
      bio: "Yup, that's my owner. U can meet him if you want",
      hasBeenSwiped: false,
      hasBeenLiked: false,
    },
    {
      name: "Bella",
      avatar: "images/six.jpg",
      age: 43,
      bio: "Yup, that's my owner. U can meet him if you want",
      hasBeenSwiped: false,
      hasBeenLiked: false,
    },
    {
      name: "Trace",
      avatar: "images/seven.jpg",
      age: 43,
      bio: "Yup, that's my owner. U can meet him if you want",
      hasBeenSwiped: false,
      hasBeenLiked: false,
    },
  ];
  export default dogs;
  